# Don't touch pls
ConfigVersion: "${project.version}"

# Debug options, don't touch unless needed
#
# DebugLevel: 0 = no debug, 1 = debug, 2 = debug with stack traces
#
DebugLevel: 0
ForcedLanguage: EN

ExperienceAmountPerClick: 10
