name: ${pluginname}
main: ${mainclass}
version: ${project.version}
api-version: ${apiversion}
author: ${developer}
description: ${description}
commands:
  jackbottles:
    description: Main command. See /jackbottles help for more information
    usage: /jackbottles
  withdrawxp:
    description: Withdraw XP from the player and store it in a bottle
    usage: /withdrawxp <amount>